name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Type Check
        run: yarn type-check

      - name: Testing
        run: yarn test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
      #  token: ${{secrets.CODECOV_TOKEN}} # required for private repos
         directory: coverage
         fail_ci_if_error: true
